"""personal\group chats model

Revision ID: 0d4243bc7957
Revises: 2a16423819eb
Create Date: 2025-04-05 16:06:52.043306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4243bc7957'
down_revision: Union[str, None] = '2a16423819eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'users', ['participant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'participant_id')
    # ### end Alembic commands ###
