"""Create initial tables

Revision ID: 1f859513478a
Revises: 
Create Date: 2025-04-03 13:28:49.733733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f859513478a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_members_chat_id_fkey', 'chat_members', type_='foreignkey')
    op.drop_constraint('chat_members_user_id_fkey', 'chat_members', type_='foreignkey')
    op.create_foreign_key(None, 'chat_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_members', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.add_column('chats', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.add_column('chats', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('chats', 'chat_type',
               existing_type=postgresql.ENUM('PRIVATE', 'GROUP', name='chattype'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('chats_created_by_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['creator_id'], ['id'])
    op.drop_column('chats', 'created_by')
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'])
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'])
    op.drop_column('messages', 'updated_at')
    op.add_column('chats', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('chats_created_by_fkey', 'chats', 'users', ['created_by'], ['id'])
    op.alter_column('chats', 'chat_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PRIVATE', 'GROUP', name='chattype'),
               existing_nullable=False)
    op.drop_column('chats', 'updated_at')
    op.drop_column('chats', 'creator_id')
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.create_foreign_key('chat_members_user_id_fkey', 'chat_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key('chat_members_chat_id_fkey', 'chat_members', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###
