"""add idempotency key

Revision ID: 7be9f3f22076
Revises: 0d4243bc7957
Create Date: 2025-04-06 15:54:33.003805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be9f3f22076'
down_revision: Union[str, None] = '0d4243bc7957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.add_column('messages', sa.Column('read_by', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    op.create_unique_constraint(None, 'messages', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_column('messages', 'read_by')
    op.drop_column('messages', 'idempotency_key')
    # ### end Alembic commands ###
